version: 2
updates:
  # Rust dependencies
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 10
    reviewers:
      - '@username' # Replace with actual username
    labels:
      - 'dependencies'
      - 'rust'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      patch-updates:
        patterns:
          - '*'
        update-types:
          - 'patch'
      minor-updates:
        patterns:
          - '*'
        update-types:
          - 'minor'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 5
    reviewers:
      - '@username' # Replace with actual username
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  # npm dependencies (for tree-sitter)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 5
    reviewers:
      - '@username' # Replace with actual username
    labels:
      - 'dependencies'
      - 'javascript'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    ignore:
      # Ignore major versions of critical dependencies
      - dependency-name: 'tree-sitter-cli'
        update-types: ['version-update:semver-major']

  # Python dependencies (if using requirements.txt)
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 5
    reviewers:
      - '@username' # Replace with actual username
    labels:
      - 'dependencies'
      - 'python'
    commit-message:
      prefix: 'chore'
      include: 'scope'
