minimum_pre_commit_version: '3.0.0'
default_language_version:
  python: python3.12
  rust: stable

repos:
  # Rust hooks
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all --
        language: system
        types: [rust]
        pass_filenames: false
        
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --workspace --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
        
      - id: cargo-check
        name: cargo check
        entry: cargo check --workspace --all-features
        language: system
        types: [rust]
        pass_filenames: false
        
      - id: cargo-test
        name: cargo test
        entry: cargo test --workspace --all-features --lib --quiet
        language: system
        types: [rust]
        pass_filenames: false
        stages: [push]

  # Tree-sitter hooks
  - repo: local
    hooks:
      - id: tree-sitter-generate
        name: tree-sitter generate
        entry: tree-sitter generate
        language: system
        files: grammar\.js$
        pass_filenames: false
        
      - id: tree-sitter-test
        name: tree-sitter test
        entry: tree-sitter test
        language: system
        files: ^(grammar\.js|test/corpus/.*\.txt)$
        pass_filenames: false
        
      - id: tree-sitter-benchmark
        name: tree-sitter benchmark
        entry: bash -c 'tree-sitter test --stat total-only | tee benchmark-results.txt && echo "=== Performance Results ===" && grep "bytes/ms" benchmark-results.txt | tail -1'
        language: system
        files: ^(grammar\.js|test/corpus/.*\.txt)$
        pass_filenames: false
        verbose: true

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: end-of-file-fixer
        exclude: ^(target/|\.git/|test/corpus/.*\.txt$)
      - id: trailing-whitespace
        exclude: ^(target/|\.git/|test/corpus/.*\.txt$)
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'master']

  # Python hooks
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12
        files: \.py$
        
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: ['--fix']
      - id: ruff-format
        
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        files: \.py$
        exclude: ^(build/|dist/|tests/)

  # JavaScript/TypeScript hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown]
        exclude: ^(target/|dist/|build/)
        
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - eslint-config-standard@17.1.0
          - eslint-plugin-import@2.29.1
          - eslint-plugin-n@16.6.1
          - eslint-plugin-promise@6.1.1

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        exclude: ^(target/|\.git/|node_modules/)

  # Shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: ['--severity=warning']

  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: ^(target/|\.git/|test/)

  # License headers
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: insert-license
        files: \.(rs|js|ts|py)$
        args:
          - --license-filepath
          - .license-header.txt
          - --comment-style
          - //
        exclude: ^(target/|build/|dist/|node_modules/)