# Rust formatting configuration for moor-echo workspace
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
reorder_imports = true
reorder_modules = true
imports_granularity = "Crate"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"

# Expressions
use_field_init_shorthand = true
use_try_shorthand = true
remove_nested_parens = true
combine_control_expr = true
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_block_trailing_comma = false
force_multiline_blocks = false
fn_params_layout = "Tall"

# Comments
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
wrap_comments = true
comment_width = 80

# Formatting
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
trailing_semicolon = true
trailing_comma = "Vertical"
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0

# Misc
inline_attribute_width = 0
merge_derives = true
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
binop_separator = "Front"
chain_width = 60
single_line_if_else_max_width = 50