# Clippy lint configuration
msrv = "1.75.0"
warn-on-all-wildcard-imports = true
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true
enum-variant-size-threshold = 200
max-fn-params-bools = 3
max-struct-bools = 3
max-trait-bounds = 5
single-char-binding-names-threshold = 4
too-many-arguments-threshold = 7
type-complexity-threshold = 250
excessive-nesting-threshold = 5