#!/bin/bash
# Demo script showing multi-line REPL capability

echo "=== Echo REPL Multi-line Demo ==="
echo "The REPL now automatically detects incomplete statements and continues on the next line."
echo ""
echo "Example 1: Object definition"
echo "When you type 'object person' and press Enter, the REPL will show '...   ' prompt"
echo "indicating it's waiting for more input until 'endobject'."
echo ""
echo "echo> object person"
echo "...   property name = \"Alice\""  
echo "...   property age = 25"
echo "...   endobject"
echo "object created"
echo ""
echo "Example 2: You can cancel multi-line input with Ctrl+C"
echo "echo> object incomplete" 
echo "...   property x = 1"
echo "...   ^C"
echo "echo>"
echo ""
echo "The REPL detects incomplete statements by checking for:"
echo "- Missing 'endobject' for object definitions"
echo "- Missing 'endif', 'endwhile', 'endfor' for control structures (when implemented)"
echo "- Other parsing errors that indicate more input is expected"